import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { FeatureErrorBoundary } from '@/components/common/FeatureErrorBoundary';
import { Button } from '@/components/ui/Button';
import {
  useDashboards,
  useCreateDashboard,
  useDeleteDashboard,
  useAutoGenerateDashboard,
} from '../hooks/useDashboards';
import { useDatasets } from '@/features/datasets/hooks/useDatasets';

export function DashboardHubPage() {
  const navigate = useNavigate();
  const { data: dashboards = [], isLoading: isLoadingHub } = useDashboards();
  const { data: datasets = [] } = useDatasets();

  const createDashboardMutation = useCreateDashboard();
  const deleteDashboardMutation = useDeleteDashboard();
  const autoGenMutation = useAutoGenerateDashboard();

  const [showCreateModal, setShowCreateModal] = useState(false);
  const [showAutoGenModal, setShowAutoGenModal] = useState(false);
  
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [selectedDatasetId, setSelectedDatasetId] = useState('');

  const handleCreate = async () => {
    if (!name.trim()) return;
    try {
      const db = await createDashboardMutation.mutateAsync({
        name: name.trim(),
        description: description.trim() || undefined,
      });
      setShowCreateModal(false);
      setName('');
      setDescription('');
      navigate(`/dashboards/${db.id}`);
    } catch (err) {
      alert('Failed to create dashboard');
    }
  };

  const handleAutoGen = async () => {
    if (!selectedDatasetId) return;
    try {
      const db = await autoGenMutation.mutateAsync(selectedDatasetId);
      setShowAutoGenModal(false);
      setSelectedDatasetId('');
      navigate(`/dashboards/${db.id}`);
    } catch (err) {
      alert('Failed to auto-generate dashboard widgets');
    }
  };

  const handleDelete = async (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    if (window.confirm('Are you sure you want to delete this dashboard?')) {
      try {
        await deleteDashboardMutation.mutateAsync(id);
      } catch (err) {
        alert('Failed to delete dashboard');
      }
    }
  };

  return (
    <FeatureErrorBoundary featureName="Dashboards Hub">
      <div className="space-y-6 text-slate-200">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold tracking-tight text-white">Executive Dashboards</h1>
            <p className="text-slate-400 text-sm mt-1">
              Select or generate dynamic visualizations from your active schemas.
            </p>
          </div>
          <div className="flex gap-3">
            <Button
              onClick={() => setShowAutoGenModal(true)}
              className="bg-slate-800 hover:bg-slate-700 text-white font-semibold py-2 px-4 border border-slate-700"
            >
              ⚡ Auto-Generate
            </Button>
            <Button
              onClick={() => setShowCreateModal(true)}
              className="bg-brand-600 hover:bg-brand-500 text-white font-semibold py-2 px-4"
            >
              + Create Dashboard
            </Button>
          </div>
        </div>

        {/* Dashboard Grid */}
        {isLoadingHub ? (
          <div className="flex justify-center items-center h-48">
            <div className="w-8 h-8 border-4 border-slate-800 border-t-brand-500 rounded-full animate-spin" />
          </div>
        ) : dashboards.length === 0 ? (
          <div className="text-center py-16 border border-dashed border-slate-800/80 rounded-2xl bg-slate-900/20 backdrop-blur-md">
            <svg className="mx-auto h-12 w-12 text-slate-500 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
            </svg>
            <h3 className="text-base font-semibold text-white">No Dashboards Yet</h3>
            <p className="text-xs text-slate-400 mt-2 max-w-sm mx-auto">
              Create a custom empty dashboard or use the auto-generator to analyze your dataset instantly.
            </p>
            <div className="flex justify-center gap-3 mt-6">
              <Button
                onClick={() => setShowAutoGenModal(true)}
                className="bg-slate-800 hover:bg-slate-700 text-white text-xs font-semibold py-1.5 px-3"
              >
                Auto-Generate
              </Button>
              <Button
                onClick={() => setShowCreateModal(true)}
                className="bg-brand-600 hover:bg-brand-500 text-white text-xs font-semibold py-1.5 px-3"
              >
                Create Blank
              </Button>
            </div>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {dashboards.map((db) => (
              <div
                key={db.id}
                onClick={() => navigate(`/dashboards/${db.id}`)}
                className="group relative flex flex-col p-5 rounded-2xl border border-slate-800/80 bg-slate-900/40 backdrop-blur-md hover:border-brand-500/50 hover:bg-slate-900/60 cursor-pointer transition-all shadow-md"
              >
                <div className="flex-1 space-y-2">
                  <div className="flex items-center gap-2">
                    <h3 className="text-sm font-semibold text-white truncate group-hover:text-brand-400 transition-colors">
                      {db.name}
                    </h3>
                    {db.is_auto_generated && (
                      <span className="text-[9px] font-bold text-brand-400 bg-brand-500/10 border border-brand-500/20 px-1.5 py-0.5 rounded uppercase shrink-0">
                        Auto
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-slate-400 line-clamp-2 min-h-[2rem]">
                    {db.description || 'No description provided.'}
                  </p>
                </div>

                <div className="mt-4 pt-4 border-t border-slate-800/60 flex items-center justify-between text-[10px] text-slate-500">
                  <span>Created {new Date(db.created_at).toLocaleDateString()}</span>
                  <button
                    onClick={(e) => handleDelete(e, db.id)}
                    className="text-slate-500 hover:text-rose-400 p-1.5 rounded hover:bg-slate-850 transition-colors shrink-0"
                    title="Delete Dashboard"
                  >
                    <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                    </svg>
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Create Dashboard Modal */}
        {showCreateModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm">
            <div className="w-full max-w-md rounded-2xl border border-slate-800 bg-slate-900 shadow-2xl p-6 space-y-4">
              <h3 className="text-lg font-semibold text-white">Create Dashboard</h3>
              
              <div className="space-y-3">
                <div>
                  <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1">
                    Dashboard Name
                  </label>
                  <input
                    type="text"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    placeholder="e.g. Q3 Sales Performance"
                    className="w-full rounded-lg border border-slate-800 bg-slate-950 px-3 py-2 text-sm text-slate-200 focus:border-brand-500 focus:outline-none"
                  />
                </div>

                <div>
                  <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1">
                    Description
                  </label>
                  <textarea
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    placeholder="e.g. Sales, opportunities and regional trends."
                    className="w-full rounded-lg border border-slate-800 bg-slate-950 px-3 py-2 text-sm text-slate-200 focus:border-brand-500 focus:outline-none h-20 resize-none"
                  />
                </div>
              </div>

              <div className="flex justify-end gap-2 pt-2">
                <Button
                  onClick={() => {
                    setShowCreateModal(false);
                    setName('');
                    setDescription('');
                  }}
                  className="bg-slate-800 hover:bg-slate-700 text-white font-semibold py-2 px-4"
                >
                  Cancel
                </Button>
                <Button
                  onClick={handleCreate}
                  disabled={!name.trim() || createDashboardMutation.isPending}
                  className="bg-brand-600 hover:bg-brand-500 text-white font-semibold py-2 px-4"
                >
                  Create
                </Button>
              </div>
            </div>
          </div>
        )}

        {/* Auto Generate Modal */}
        {showAutoGenModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm">
            <div className="w-full max-w-md rounded-2xl border border-slate-800 bg-slate-900 shadow-2xl p-6 space-y-4">
              <h3 className="text-lg font-semibold text-white">Auto-Generate Analytics Dashboard</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                Select a dataset. The rules engine will scan your logical schemas and create recommended charts automatically.
              </p>
              
              <div className="space-y-3">
                <div>
                  <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1">
                    Select Source Schema
                  </label>
                  <select
                    value={selectedDatasetId}
                    onChange={(e) => setSelectedDatasetId(e.target.value)}
                    className="w-full rounded-lg border border-slate-800 bg-slate-950 px-3 py-2 text-sm text-slate-200 focus:border-brand-500 focus:outline-none"
                  >
                    <option value="">-- Choose uploaded file --</option>
                    {datasets.map((d) => (
                      <option key={d.id} value={d.id}>
                        {d.name} (.{d.file_format})
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              <div className="flex justify-end gap-2 pt-2">
                <Button
                  onClick={() => {
                    setShowAutoGenModal(false);
                    setSelectedDatasetId('');
                  }}
                  className="bg-slate-800 hover:bg-slate-700 text-white font-semibold py-2 px-4"
                >
                  Cancel
                </Button>
                <Button
                  onClick={handleAutoGen}
                  disabled={!selectedDatasetId || autoGenMutation.isPending}
                  className="bg-brand-600 hover:bg-brand-500 text-white font-semibold py-2 px-4"
                >
                  ⚡ Generate
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>
    </FeatureErrorBoundary>
  );
}
