import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import {
  listDashboards,
  getDashboard,
  createDashboard,
  updateDashboard,
  deleteDashboard,
  addWidget,
  deleteWidget,
  getWidgetData,
  autoGenerateDashboard,
  getPreviewData,
} from '../api';
import type { Widget } from '../types';

export const dashboardKeys = {
  all: ['dashboards'] as const,
  lists: () => [...dashboardKeys.all, 'list'] as const,
  details: () => [...dashboardKeys.all, 'detail'] as const,
  detail: (id: string) => [...dashboardKeys.details(), id] as const,
  widgetData: (widgetId: string) => [...dashboardKeys.all, 'widget-data', widgetId] as const,
};

export function useDashboards() {
  return useQuery({
    queryKey: dashboardKeys.lists(),
    queryFn: listDashboards,
  });
}

export function useDashboard(id: string) {
  return useQuery({
    queryKey: dashboardKeys.detail(id),
    queryFn: () => getDashboard(id),
    enabled: !!id,
  });
}

export function useCreateDashboard() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ name, description }: { name: string; description?: string }) =>
      createDashboard(name, description),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: dashboardKeys.lists() });
    },
  });
}

export function useUpdateDashboard(id: string) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ name, description }: { name?: string; description?: string }) =>
      updateDashboard(id, name, description),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: dashboardKeys.lists() });
      queryClient.invalidateQueries({ queryKey: dashboardKeys.detail(id) });
    },
  });
}

export function useDeleteDashboard() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: deleteDashboard,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: dashboardKeys.lists() });
    },
  });
}

export function useAddWidget(dashboardId: string) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (widget: Omit<Widget, 'id' | 'dashboard_id' | 'created_at' | 'updated_at'>) =>
      addWidget(dashboardId, widget),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: dashboardKeys.detail(dashboardId) });
    },
  });
}

export function useDeleteWidget(dashboardId: string) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (widgetId: string) => deleteWidget(dashboardId, widgetId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: dashboardKeys.detail(dashboardId) });
    },
  });
}

export function useWidgetData(widgetId: string) {
  return useQuery({
    queryKey: dashboardKeys.widgetData(widgetId),
    queryFn: () => getWidgetData(widgetId),
    enabled: !!widgetId,
    staleTime: 5000, // cache for 5 seconds to reduce pandas file reads
  });
}

export function useAutoGenerateDashboard() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (datasetId: string) => autoGenerateDashboard(datasetId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: dashboardKeys.lists() });
    },
  });
}

export function usePreviewData(
  datasetId: string,
  xAxis: string,
  yAxis: string,
  aggregateFunc?: string
) {
  return useQuery({
    queryKey: ['dashboards', 'preview-data', datasetId, xAxis, yAxis, aggregateFunc],
    queryFn: () => getPreviewData(datasetId, xAxis, yAxis, aggregateFunc),
    enabled: !!datasetId && !!xAxis && !!yAxis,
    staleTime: 0,
  });
}
