import { apiClient } from '@/services/api';
import type { Dashboard, Widget, WidgetDataResponse } from '../types';

export async function listDashboards(): Promise<Dashboard[]> {
  const response = await apiClient.get<Dashboard[]>('/dashboards');
  return response.data;
}

export async function getDashboard(id: string): Promise<Dashboard> {
  const response = await apiClient.get<Dashboard>(`/dashboards/${id}`);
  return response.data;
}

export async function createDashboard(name: string, description?: string): Promise<Dashboard> {
  const response = await apiClient.post<Dashboard>('/dashboards', {
    name,
    description,
  });
  return response.data;
}

export async function updateDashboard(id: string, name?: string, description?: string): Promise<Dashboard> {
  const response = await apiClient.patch<Dashboard>(`/dashboards/${id}`, {
    name,
    description,
  });
  return response.data;
}

export async function deleteDashboard(id: string): Promise<void> {
  await apiClient.delete(`/dashboards/${id}`);
}

export async function addWidget(
  dashboardId: string,
  widget: Omit<Widget, 'id' | 'dashboard_id' | 'created_at' | 'updated_at'>
): Promise<Widget> {
  const response = await apiClient.post<Widget>(`/dashboards/${dashboardId}/widgets`, widget);
  return response.data;
}

export async function deleteWidget(dashboardId: string, widgetId: string): Promise<void> {
  await apiClient.delete(`/dashboards/${dashboardId}/widgets/${widgetId}`);
}

export async function getWidgetData(widgetId: string): Promise<WidgetDataResponse> {
  const response = await apiClient.get<WidgetDataResponse>(`/dashboards/widgets/${widgetId}/data`);
  return response.data;
}

export async function autoGenerateDashboard(datasetId: string): Promise<Dashboard> {
  const response = await apiClient.post<Dashboard>(`/dashboards/auto-generate/${datasetId}`);
  return response.data;
}

export async function getPreviewData(
  datasetId: string,
  xAxis: string,
  yAxis: string,
  aggregateFunc?: string
): Promise<{ data: Array<Record<string, any>> }> {
  const response = await apiClient.get<{ data: Array<Record<string, any>> }>('/dashboards/preview-data', {
    params: {
      dataset_id: datasetId,
      x_axis: xAxis,
      y_axis: yAxis,
      aggregate_func: aggregateFunc,
    },
  });
  return response.data;
}
